""" Python Programming """

""" Topics"""
"""1.Getting Started with Python Programming"""
"""1.Introduction to Python"""
"""2.Compiler vs Interpreter Language"""
"""3.Setting up Python work environment"""
"""4.Hello World in Python (running Python codes in 3 ways)"""
"""5.Print Statement"""
"""6.Variables"""
"""7.Comments"""
"""8.Data Types"""
"""9.Getting the input from the user."""
